Resolve #1
unitprotocol/wrapped-assets pull request #2
Opened 2021-05-18 09:17 UTC by 34x4p08

Resolve #1

2021-05-18 10:28 UTC, Eenae requested changes
Transfers handling should be improved.

2021-05-18 10:28 UTC, Eenae commented on contracts/WrappedAsset.sol
> +        uint balanceAfter = underlying.balanceOf(address(this));
If the `underlying` gives some dividends to `this` before actual balance update, they are attributed to `msg.sender`. That's bad.

2021-05-18 10:28 UTC, Eenae commented on contracts/WrappedAsset.sol
> +        uint balanceAfter = underlying.balanceOf(address(this));
If the `underlying` withhold some fee from `this` on transfer, the fee is not charged from `msg.sender` but stays on his balance, meaning we become a bit insolvent. That's bad.

2021-05-18 10:28 UTC, Eenae commented on contracts/WrappedAssetFactory.sol
> +        string memory _nameOverride,
`calldata`?

2021-05-18 10:28 UTC, Eenae commented on contracts/WrappedAsset.sol
> +        return (keccak256(abi.encodePacked((a))) == keccak256(abi.encodePacked((""))));
`bytes(a).length == 0`?

2021-05-18 10:28 UTC, Eenae commented on contracts/WrappedAsset.sol
> +        _decimals = _decimalsOverride == 0 ? ERC20(_underlying).decimals() : _decimalsOverride;
Here there is no way to override decimals to `0` )

2021-05-18 10:28 UTC, Eenae commented on contracts/WrappedAsset.sol
> +            : _nameOverride;
As an alternative c++ style solution, the base ctor may be invoked with results from `internal view` functions which properly construct attributes. So there is no need in shadowing slots.

2021-05-18 18:10 UTC, 34x4p08 commented on contracts/WrappedAsset.sol
> +        uint balanceAfter = underlying.balanceOf(address(this));
Can you provide an example of this use case?

2021-05-18 18:44 UTC, 34x4p08 commented on contracts/WrappedAsset.sol
> +            : _nameOverride;
Moved to factory

2021-05-18 18:45 UTC, 34x4p08 commented on contracts/WrappedAssetFactory.sol
> +        string memory _nameOverride,
+

2021-05-18 18:45 UTC, 34x4p08 commented on contracts/WrappedAsset.sol
> +        return (keccak256(abi.encodePacked((a))) == keccak256(abi.encodePacked((""))));
+

2021-05-18 18:46 UTC, 34x4p08 commented on contracts/WrappedAsset.sol
> +        _decimals = _decimalsOverride == 0 ? ERC20(_underlying).decimals() : _decimalsOverride;
Agree

2021-05-18 18:46 UTC, 34x4p08 commented on contracts/WrappedAsset.sol
> +        uint balanceAfter = underlying.balanceOf(address(this));
Fixed

2021-05-19 10:09 UTC, Eenae commented on contracts/WrappedAsset.sol
> +        uint balanceAfter = underlying.balanceOf(address(this));
https://github.com/mixbytes/solidity/blob/master/contracts/token/DividendToken.sol#L69

2021-05-19 10:31 UTC, Eenae commented on contracts/WrappedAsset.sol
> +        uint balanceAfter = underlying.balanceOf(address(this));
What if the actual transfer amount is greater that `amount`?

2021-05-19 15:42 UTC, 34x4p08 commented on contracts/WrappedAsset.sol
> +        uint balanceAfter = underlying.balanceOf(address(this));
- We shouldn't worry about super rare use cases to not overload wrapper code
- It's unwanted to use dividend assets as collateral on Unit, compounding assets are preferred instead

2021-05-19 15:48 UTC, 34x4p08 commented on contracts/WrappedAsset.sol
> +        uint balanceAfter = underlying.balanceOf(address(this));
Sounds like incorrect transfer logic, so we will not use such assets as collateral

2021-05-19 16:17 UTC, Eenae commented on contracts/WrappedAsset.sol
> +        uint balanceAfter = underlying.balanceOf(address(this));
Btw, vulnerable to reentrancy if `underlying.transferFrom` allows external calls.

2021-05-19 17:45 UTC, 34x4p08 commented on contracts/WrappedAsset.sol
> +        uint balanceAfter = underlying.balanceOf(address(this));
ReentrancyGuard added

2021-05-19 17:57 UTC, Eenae approved these changes
Ok, with the non-standard tokens proviso.

2021-05-19 20:14 UTC, merged